### ISSUE TITLE
wgpu integration example fails to build in release mode

### ISSUE THREAD

**Issue by imgurbot12** [iced-rs/iced#2447]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is this issue related to iced?

- [X] My hardware is compatible and my graphics drivers are up-to-date.

### What happened?

The existing [wgpu integration example](https://github.com/iced-rs/iced/tree/master/examples/integration) on the latest master branch fails to build in release mode due to unexpected trait issues.
I'm honestly confused by this as I have no idea why the debug version vs release would be so different to cause these errors.

### What is the expected behavior?

The example should compile in release mode just like it does in debug.

### Version

master

### Operating System

Linux

### Do you have any log output?

```shell
Compiling glyphon v0.5.0 (https://github.com/hecrj/glyphon.git?rev=f07e7bab705e69d39a5e6e52c73039a93c4552f8#f07e7bab)
   Compiling iced_widget v0.13.0-dev (/home/andrew/Code/github/iced/widget)
   Compiling iced_wgpu v0.13.0-dev (/home/andrew/Code/github/iced/wgpu)
error[E0277]: the trait bound `(): iced_renderer::iced_core::Renderer` is not satisfied
  --> widget/src/themer.rs:24:15
   |
24 |     Renderer: crate::core::Renderer,
   |               ^^^^^^^^^^^^^^^^^^^^^ the trait `iced_renderer::iced_core::Renderer` is not implemented for `()`
   |
   = help: the trait `iced_renderer::iced_core::Renderer` is implemented for `iced_renderer::fallback::Renderer<A, B>`

error[E0277]: the trait bound `(): iced_renderer::iced_core::Renderer` is not satisfied
  --> widget/src/button.rs:51:15
   |
51 |     Renderer: crate::core::Renderer,
   |               ^^^^^^^^^^^^^^^^^^^^^ the trait `iced_renderer::iced_core::Renderer` is not implemented for `()`
   |
   = help: the trait `iced_renderer::iced_core::Renderer` is implemented for `iced_renderer::fallback::Renderer<A, B>`

error[E0277]: the trait bound `(): iced_renderer::iced_core::text::Renderer` is not satisfied
  --> widget/src/checkbox.rs:41:15
   |
41 |     Renderer: text::Renderer,
   |               ^^^^^^^^^^^^^^ the trait `iced_renderer::iced_core::text::Renderer` is not implemented for `()`
   |
   = help: the trait `iced_renderer::iced_core::text::Renderer` is implemented for `iced_renderer::fallback::Renderer<A, B>`

error[E0277]: the trait bound `(): iced_renderer::iced_core::text::Renderer` is not satisfied
  --> widget/src/combo_box.rs:36:15
   |
36 |     Renderer: text::Renderer,
   |               ^^^^^^^^^^^^^^ the trait `iced_renderer::iced_core::text::Renderer` is not implemented for `()`
   |
   = help: the trait `iced_renderer::iced_core::text::Renderer` is implemented for `iced_renderer::fallback::Renderer<A, B>`

error[E0277]: the trait bound `(): iced_renderer::iced_core::Renderer` is not satisfied
  --> widget/src/container.rs:29:15
   |
29 |     Renderer: core::Renderer,
   |               ^^^^^^^^^^^^^^ the trait `iced_renderer::iced_core::Renderer` is not implemented for `()`
   |
   = help: the trait `iced_renderer::iced_core::Renderer` is implemented for `iced_renderer::fallback::Renderer<A, B>`

error[E0277]: the trait bound `(): iced_renderer::iced_core::text::Renderer` is not satisfied
  --> widget/src/overlay/menu.rs:29:15
   |
29 |     Renderer: text::Renderer,
   |               ^^^^^^^^^^^^^^ the trait `iced_renderer::iced_core::text::Renderer` is not implemented for `()`
   |
   = help: the trait `iced_renderer::iced_core::text::Renderer` is implemented for `iced_renderer::fallback::Renderer<A, B>`

error[E0277]: the trait bound `(): iced_renderer::iced_core::Renderer` is not satisfied
   --> widget/src/pane_grid.rs:106:15
    |
106 |     Renderer: core::Renderer,
    |               ^^^^^^^^^^^^^^ the trait `iced_renderer::iced_core::Renderer` is not implemented for `()`
    |
    = help: the trait `iced_renderer::iced_core::Renderer` is implemented for `iced_renderer::fallback::Renderer<A, B>`

error[E0277]: the trait bound `(): iced_renderer::iced_core::Renderer` is not satisfied
  --> widget/src/pane_grid/content.rs:24:15
   |
24 |     Renderer: core::Renderer,
   |               ^^^^^^^^^^^^^^ the trait `iced_renderer::iced_core::Renderer` is not implemented for `()`
   |
   = help: the trait `iced_renderer::iced_core::Renderer` is implemented for `iced_renderer::fallback::Renderer<A, B>`

error[E0277]: the trait bound `(): iced_renderer::iced_core::Renderer` is not satisfied
  --> widget/src/pane_grid/title_bar.rs:24:15
   |
24 |     Renderer: core::Renderer,
   |               ^^^^^^^^^^^^^^ the trait `iced_renderer::iced_core::Renderer` is not implemented for `()`
   |
   = help: the trait `iced_renderer::iced_core::Renderer` is implemented for `iced_renderer::fallback::Renderer<A, B>`

error[E0277]: the trait bound `(): iced_renderer::iced_core::text::Renderer` is not satisfied
  --> widget/src/pick_list.rs:36:15
   |
36 |     Renderer: text::Renderer,
   |               ^^^^^^^^^^^^^^ the trait `iced_renderer::iced_core::text::Renderer` is not implemented for `()`
   |
   = help: the trait `iced_renderer::iced_core::text::Renderer` is implemented for `iced_renderer::fallback::Renderer<A, B>`

error[E0277]: the trait bound `(): iced_renderer::iced_core::text::Renderer` is not satisfied
  --> widget/src/radio.rs:73:15
   |
73 |     Renderer: text::Renderer,
   |               ^^^^^^^^^^^^^^ the trait `iced_renderer::iced_core::text::Renderer` is not implemented for `()`
   |
   = help: the trait `iced_renderer::iced_core::text::Renderer` is implemented for `iced_renderer::fallback::Renderer<A, B>`

error[E0277]: the trait bound `(): iced_renderer::iced_core::Renderer` is not satisfied
  --> widget/src/scrollable.rs:32:15
   |
32 |     Renderer: core::Renderer,
   |               ^^^^^^^^^^^^^^ the trait `iced_renderer::iced_core::Renderer` is not implemented for `()`
   |
   = help: the trait `iced_renderer::iced_core::Renderer` is implemented for `iced_renderer::fallback::Renderer<A, B>`

error[E0277]: the trait bound `(): iced_renderer::iced_core::text::Renderer` is not satisfied
  --> widget/src/text_editor.rs:36:15
   |
36 |     Renderer: text::Renderer,
   |               ^^^^^^^^^^^^^^ the trait `iced_renderer::iced_core::text::Renderer` is not implemented for `()`
   |
   = help: the trait `iced_renderer::iced_core::text::Renderer` is implemented for `iced_renderer::fallback::Renderer<A, B>`

error[E0277]: the trait bound `(): iced_renderer::iced_core::text::Renderer` is not satisfied
   --> widget/src/text_editor.rs:181:8
    |
181 |     R: text::Renderer;
    |        ^^^^^^^^^^^^^^ the trait `iced_renderer::iced_core::text::Renderer` is not implemented for `()`
    |
    = help: the trait `iced_renderer::iced_core::text::Renderer` is implemented for `iced_renderer::fallback::Renderer<A, B>`

error[E0277]: the trait bound `(): iced_renderer::iced_core::text::Renderer` is not satisfied
  --> widget/src/text_input.rs:64:15
   |
64 |     Renderer: text::Renderer,
   |               ^^^^^^^^^^^^^^ the trait `iced_renderer::iced_core::text::Renderer` is not implemented for `()`
   |
   = help: the trait `iced_renderer::iced_core::text::Renderer` is implemented for `iced_renderer::fallback::Renderer<A, B>`

error[E0277]: the trait bound `(): iced_renderer::iced_core::text::Renderer` is not satisfied
  --> widget/src/toggler.rs:39:15
   |
39 |     Renderer: text::Renderer,
   |               ^^^^^^^^^^^^^^ the trait `iced_renderer::iced_core::text::Renderer` is not implemented for `()`
   |
   = help: the trait `iced_renderer::iced_core::text::Renderer` is implemented for `iced_renderer::fallback::Renderer<A, B>`

error[E0277]: the trait bound `(): iced_renderer::iced_core::text::Renderer` is not satisfied
  --> widget/src/tooltip.rs:24:15
   |
24 |     Renderer: text::Renderer,
   |               ^^^^^^^^^^^^^^ the trait `iced_renderer::iced_core::text::Renderer` is not implemented for `()`
   |
   = help: the trait `iced_renderer::iced_core::text::Renderer` is implemented for `iced_renderer::fallback::Renderer<A, B>`

error[E0599]: the function or associated item `new` exists for struct `Column<'a, Message, Renderer>`, but its trait bounds were not satisfied
   --> widget/src/column.rs:160:15
    |
15  | pub struct Column<'a, Message, Theme = crate::Theme, Renderer = crate::Renderer>
    | -------------------------------------------------------------------------------- function or associated item `new` not found for this struct
...
160 |         Self::new()
    |               ^^^ function or associated item cannot be called on `Column<'a, Message, Renderer>` due to unsatisfied trait bounds
    |
note: if you're trying to build a new `column::Column<'a, Message, Renderer>` consider using one of the following associated functions:
      column::Column::<'a, Message, Theme, Renderer>::new
      column::Column::<'a, Message, Theme, Renderer>::with_capacity
      column::Column::<'a, Message, Theme, Renderer>::with_children
      column::Column::<'a, Message, Theme, Renderer>::from_vec
   --> widget/src/column.rs:32:5
    |
32  |       pub fn new() -> Self {
    |       ^^^^^^^^^^^^^^^^^^^^
...
37  |       pub fn with_capacity(capacity: usize) -> Self {
    |       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
...
42  | /     pub fn with_children(
43  | |         children: impl IntoIterator<Item = Element<'a, Message, Theme, Renderer>>,
44  | |     ) -> Self {
    | |_____________^
...
57  | /     pub fn from_vec(
58  | |         children: Vec<Element<'a, Message, Theme, Renderer>>,
59  | |     ) -> Self {
    | |_____________^
note: trait bound `(): iced_renderer::iced_core::Renderer` was not satisfied
   --> widget/src/column.rs:29:15
    |
27  | impl<'a, Message, Theme, Renderer> Column<'a, Message, Theme, Renderer>
    |                                    ------------------------------------
28  | where
29  |     Renderer: crate::core::Renderer,
    |               ^^^^^^^^^^^^^^^^^^^^^ unsatisfied trait bound introduced here
    = help: items from traits can only be used if the trait is implemented and in scope
    = note: the following traits define an item `new`, perhaps you need to implement one of them:
            candidate #1: `iced_renderer::iced_graphics::Compositor`
            candidate #2: `read_fonts::tables::variations::TupleDelta`
            candidate #3: `Highlighter`
            candidate #4: `iced_runtime::iced_futures::Executor`

error[E0599]: the function or associated item `new` exists for struct `Row<'a, Message, Renderer>`, but its trait bounds were not satisfied
   --> widget/src/row.rs:151:15
    |
15  | pub struct Row<'a, Message, Theme = crate::Theme, Renderer = crate::Renderer> {
    | ----------------------------------------------------------------------------- function or associated item `new` not found for this struct
...
151 |         Self::new()
    |               ^^^ function or associated item cannot be called on `Row<'a, Message, Renderer>` due to unsatisfied trait bounds
    |
note: if you're trying to build a new `Row<'a, Message, Renderer>` consider using one of the following associated functions:
      Row::<'a, Message, Theme, Renderer>::new
      Row::<'a, Message, Theme, Renderer>::with_capacity
      Row::<'a, Message, Theme, Renderer>::with_children
      Row::<'a, Message, Theme, Renderer>::from_vec
   --> widget/src/row.rs:30:5
    |
30  |       pub fn new() -> Self {
    |       ^^^^^^^^^^^^^^^^^^^^
...
35  |       pub fn with_capacity(capacity: usize) -> Self {
    |       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
...
40  | /     pub fn with_children(
41  | |         children: impl IntoIterator<Item = Element<'a, Message, Theme, Renderer>>,
42  | |     ) -> Self {
    | |_____________^
...
55  | /     pub fn from_vec(
56  | |         children: Vec<Element<'a, Message, Theme, Renderer>>,
57  | |     ) -> Self {
    | |_____________^
note: trait bound `(): iced_renderer::iced_core::Renderer` was not satisfied
   --> widget/src/row.rs:27:15
    |
25  | impl<'a, Message, Theme, Renderer> Row<'a, Message, Theme, Renderer>
    |                                    ---------------------------------
26  | where
27  |     Renderer: crate::core::Renderer,
    |               ^^^^^^^^^^^^^^^^^^^^^ unsatisfied trait bound introduced here
    = help: items from traits can only be used if the trait is implemented and in scope
    = note: the following traits define an item `new`, perhaps you need to implement one of them:
            candidate #1: `iced_renderer::iced_graphics::Compositor`
            candidate #2: `read_fonts::tables::variations::TupleDelta`
            candidate #3: `Highlighter`
            candidate #4: `iced_runtime::iced_futures::Executor`

error[E0599]: the function or associated item `new` exists for struct `Stack<'a, Message, Renderer>`, but its trait bounds were not satisfied
   --> widget/src/stack.rs:124:15
    |
21  | pub struct Stack<'a, Message, Theme = crate::Theme, Renderer = crate::Renderer>
    | ------------------------------------------------------------------------------- function or associated item `new` not found for this struct
...
124 |         Self::new()
    |               ^^^ function or associated item cannot be called on `Stack<'a, Message, Renderer>` due to unsatisfied trait bounds
    |
note: if you're trying to build a new `stack::Stack<'a, Message, Renderer>` consider using one of the following associated functions:
      stack::Stack::<'a, Message, Theme, Renderer>::new
      stack::Stack::<'a, Message, Theme, Renderer>::with_capacity
      stack::Stack::<'a, Message, Theme, Renderer>::with_children
      stack::Stack::<'a, Message, Theme, Renderer>::from_vec
   --> widget/src/stack.rs:33:5
    |
33  |       pub fn new() -> Self {
    |       ^^^^^^^^^^^^^^^^^^^^
...
38  |       pub fn with_capacity(capacity: usize) -> Self {
    |       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
...
43  | /     pub fn with_children(
44  | |         children: impl IntoIterator<Item = Element<'a, Message, Theme, Renderer>>,
45  | |     ) -> Self {
    | |_____________^
...
58  | /     pub fn from_vec(
59  | |         children: Vec<Element<'a, Message, Theme, Renderer>>,
60  | |     ) -> Self {
    | |_____________^
note: trait bound `(): iced_renderer::iced_core::Renderer` was not satisfied
   --> widget/src/stack.rs:30:15
    |
28  | impl<'a, Message, Theme, Renderer> Stack<'a, Message, Theme, Renderer>
    |                                    -----------------------------------
29  | where
30  |     Renderer: crate::core::Renderer,
    |               ^^^^^^^^^^^^^^^^^^^^^ unsatisfied trait bound introduced here
    = help: items from traits can only be used if the trait is implemented and in scope
    = note: the following traits define an item `new`, perhaps you need to implement one of them:
            candidate #1: `iced_renderer::iced_graphics::Compositor`
            candidate #2: `read_fonts::tables::variations::TupleDelta`
            candidate #3: `Highlighter`
            candidate #4: `iced_runtime::iced_futures::Executor`

error[E0599]: the function or associated item `new` exists for struct `Column<'a, Key, Message, Renderer>`, but its trait bounds were not satisfied
   --> widget/src/keyed/column.rs:177:15
    |
16  | / pub struct Column<
17  | |     'a,
18  | |     Key,
19  | |     Message,
20  | |     Theme = crate::Theme,
21  | |     Renderer = crate::Renderer,
22  | | > where
    | |_- function or associated item `new` not found for this struct
...
177 |           Self::new()
    |                 ^^^ function or associated item cannot be called on `Column<'a, Key, Message, Renderer>` due to unsatisfied trait bounds
    |
note: if you're trying to build a new `keyed::column::Column<'a, Key, Message, Renderer>` consider using one of the following associated functions:
      keyed::column::Column::<'a, Key, Message, Theme, Renderer>::new
      keyed::column::Column::<'a, Key, Message, Theme, Renderer>::from_vecs
      keyed::column::Column::<'a, Key, Message, Theme, Renderer>::with_capacity
      keyed::column::Column::<'a, Key, Message, Theme, Renderer>::with_children
   --> widget/src/keyed/column.rs:42:5
    |
42  |       pub fn new() -> Self {
    |       ^^^^^^^^^^^^^^^^^^^^
...
53  | /     pub fn from_vecs(
54  | |         keys: Vec<Key>,
55  | |         children: Vec<Element<'a, Message, Theme, Renderer>>,
56  | |     ) -> Self {
    | |_____________^
...
70  |       pub fn with_capacity(capacity: usize) -> Self {
    |       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
...
78  | /     pub fn with_children(
79  | |         children: impl IntoIterator<
80  | |             Item = (Key, Element<'a, Message, Theme, Renderer>),
81  | |         >,
82  | |     ) -> Self {
    | |_____________^
note: trait bound `(): iced_renderer::iced_core::Renderer` was not satisfied
   --> widget/src/keyed/column.rs:39:15
    |
36  |     Column<'a, Key, Message, Theme, Renderer>
    |     -----------------------------------------
...
39  |     Renderer: crate::core::Renderer,
    |               ^^^^^^^^^^^^^^^^^^^^^ unsatisfied trait bound introduced here
    = help: items from traits can only be used if the trait is implemented and in scope
    = note: the following traits define an item `new`, perhaps you need to implement one of them:
            candidate #1: `iced_renderer::iced_graphics::Compositor`
            candidate #2: `read_fonts::tables::variations::TupleDelta`
            candidate #3: `Highlighter`
            candidate #4: `iced_runtime::iced_futures::Executor`

Some errors have detailed explanations: E0277, E0599.
For more information about an error, try `rustc --explain E0277`.
error: could not compile `iced_widget` (lib) due to 21 previous errors
warning: build failed, waiting for other jobs to finish...
```

**Comment by Mingun** [comment]
Some strange build issues can be fixed by cleaning up outdated build artifacts. This seems the case here. Try to run `cargo clean`

**Comment by imgurbot12** [comment]
Hey @Mingun, thanks for the response. 

I ran a cargo clean. In fact i went a step further and deleted the entire clone, cloned it from scratch and then ran a release build again and got the same error. am i somehow failing to clean a cache somewhere else. total series of commands:
```bash
cargo clean
cd ..
rm -rf iced
git clone https://github.com/iced-rs/iced.git
cd iced/examples/integration
cargo build --release
```

**Comment by imgurbot12** [comment]
hey @hecrj, im sorry to be a bother but why was this closed? was there a fix for the related issue? I'm still getting compilation errors even now with no clear answer as to why.

**Comment by bob448** [comment]
just toss it away and pretend like this bug never happened, huh?

**Comment by hecrj** [comment]
@bob448 You mean the bug I fixed almost a year ago? Just one day afer the issue was opened? You are welcome.

I can't fix brains, unfortunately.

**Comment by imgurbot12** [comment]
> I can't fix brains, unfortunately.

I was fine with leaving this as closed since I basically moved on and simply decided not to upgrade whilst having this issue. It's been so long since this was even relevant that I have no possibility of remembering all the specifics but whats written is what happened.

I searched for existing issues and there were none, nobody told me it was a duplicate. I followed the advice given by another and it did not work and then suddenly it was closed without warning or explanation. Even after the supposed fix, and referencing master in cargo, clearing everything out and testing again I still had issues. All of that I can forgive assuming I could come back to the project and it would probably be fixed once I came back to it and needed it to work.

Your random comment nearly a full year is extremely unprofessional and genuinely I have to ask myself if that comment was projection considering there is zero value in posting something as asinine a response as that for something so completely irrelevant and out of touch.

**Comment by airstrike** [comment]
> > I can't fix brains, unfortunately.
> 
> I was fine with leaving this as closed since I basically moved on and simply decided not to upgrade whilst having this issue. It's been so long since this was even relevant that I have no possibility of remembering all the specifics but whats written is what happened.
> 
> I searched for existing issues and there were none, nobody told me it was a duplicate. I followed the advice given by another and it did not work and then suddenly it was closed without warning or explanation. Even after the supposed fix, and referencing master in cargo, clearing everything out and testing again I still had issues. All of that I can forgive assuming I could come back to the project and it would probably be fixed once I came back to it and needed it to work.
> 
> Your random comment nearly a full year is extremely unprofessional and genuinely I have to ask myself if that comment was projection considering there is zero value in posting something as asinine and out of touch a response as that for something so completely irrelevant.

@imgurbot12 FYI you're missing the fact that the comment was not directed at you, but rather as a reply to @bob448 who did make a comment _today_ accusing the maintainer of "pretending the bug never happened, huh?" even though it was fixed within 24 hours of your original issue being opened.

I think if you want to label anything a "random comment nearly a full year" later as unprofessional, that's the comment you should point fingers at

**Comment by imgurbot12** [comment]
Considering there was no follow up to my original question after the issue is closed I felt much the same way as @bob448 since as I explained it was still not working even after the patch in my testing if I recall correctly. It may be fixed now but that's besides the point. Bob could've been more polite in the manner of his address but there is fault in the complete lack of communication and instead of admitting to anything @hecrj resorted to personal insults and ad-hominem.

If that was the intent then fair enough but that's not how I interpreted it. Still unprofessional and undeserved.

**Comment by airstrike** [comment]
The only follow-up that was needed was that the issue was marked as completed with a commit which addressed it: https://github.com/iced-rs/iced/commit/d92e0f7bba8959384467048c7eca84b4b8a7195f

The example works in release here, both on Linux and Mac OS. No one else has reported this issue. You yourself said you had moved on. Why do you feel entitled to a response if you hadn't even bothered to try to run this in a year? I actually bothered to install a Debian VM just to make sure what I'm saying about reproducibility is an accurate statement to the best of my abilities.

> Bob could've been more polite in the manner of his address but there is fault in the complete lack of communication and instead of admitting to anything @hecrj resorted to personal insults and ad-hominem.

I find this bit fascinating. "Bob could have been more polite?" His comment was 100% a personal attack, except in a roundabout, passive-aggressive way, about an issue that literally does not exist. Expecting kindness after that is wild. It's like going into someone's house, trashing it and then wanting the host to be accommodating and understanding.

"Complete lack of communication"? The issue was fixed in 24 hours! There's nothing further to discuss.

"Instead of admitting to anything"? What is there to admit? Even if the issue still existed, don't you agree it's fairly easy to miss a reply in some issue that has already been closed. Look at how many issues, commits, and comments the project has. Have you never had someone forget to reply to you, miss a text, email, comment? If you really wanted an answer, why not follow-up yourself?

Nobody here has the *right* to be replied to, because that would imply someone else has an *obligation* to reply, which isn't the case. I think we all certainly strive to communicate as much as possible, but it's not an obligation.

I encourage you to review why you think you're entitled to anything from a free project and why you think anyone throwing thoughtless accusations unsupported by any factual data—without doing any of the legwork to double check their assumptions—deserves anything other than a harsh response back by the people in charge of the project.

**Comment by imgurbot12** [comment]
I have to wonder if this argument is in bad faith with how one sided your position is here. Here's the timeline as I see it.

1. issue was created.
2. Minigun recommends potential solution
3. Minigun solution does not work and I post an explanation on my attempts
4. hecrj makes a commit change and closes the issue without comment (suppsedly resolving the issue)
5. I test changes in master at the time and still encounter errors. (this includes doing cargo-clean/re-cloning repo/etc...)
6. I post a comment asking why issue is closed since I am still encountering issues and no single explanation or comment was given whatsoever
7. I give up since I assume I'm doing something wrong and its clear the devs do not want to bother with me since there was no verbal communication at all, only github notifications of action.

8. NEARLY ONE YEAR LATER, a stranger (potentially with a similar issue, i have no idea who bob is) finds this issue and similarly sees that hecrj left this issue "on read" and hasn't seemingly fixed the root issue considering my comment or at least not addressed my comments.

9. hecrj then decides to be passive aggressive and attack someone potentially looking for assistance.

**Comment by edwloef** [comment]
> I ran a cargo clean. In fact i went a step further and deleted the entire clone, cloned it from scratch and then ran a release build again and got the same error. Am i somehow failing to clean a cache somewhere else?

Maybe you could try clearing out your cargo registry? I've had issues in the past where I've unintentionally edited files that cargo downloaded, which then caused build errors.

**Comment by imgurbot12** [comment]
As of now, on a new machine, the latest master does compile in release mode for me so its working as of the latest commit if that was a concern lol. At the time it likely was some sort of internal cargo registry issue or something persisting a bad build, but it was rather persistent. I appreciate the advice thank you.

**Comment by hecrj** [comment]
@imgurbot12 Bfff... What a bunch of manipulative bullshit.

Skill issue. Go blame your sheer incompetence somewhere else.
