### ISSUE TITLE
Stop scrollview from consuming the interface

### ISSUE THREAD

**Issue by rnd-ash** [iced-rs/iced#715]
My application has a main UI page which is broken down into 2 parts:

1. main interface which can change
2. Bottom status bar which is permanently on screen

With the UI with explain enabled, you can see this:
![image](https://user-images.githubusercontent.com/14551965/105879691-64a61200-5ffa-11eb-8786-a1fdcaafe474.png)

Under log view in this image is a scrollview. Below that is a space followed by the status bar. It is drawn like so:

```rust
let mut c: Element<_> = Column::new()
                .push(view_contents) // Draw the custom view on screen
                .push(Space::with_height(Length::Fill)) // Pad the gap
                .push(Rule::horizontal(1)) // Draw a line
                .push(s_bar) // Draw the status bar
                .into();
if themes::is_debug() {
    c = c.explain(iced::Color::BLACK);
}
container(c)
    .height(Length::Fill)
    .width(Length::Fill)
    .into()

```

however, when I keep adding elements to the scrollview, this eventually happens:
![image](https://user-images.githubusercontent.com/14551965/105879941-ac2c9e00-5ffa-11eb-88f1-b644fabd6120.png)

Here, the scrollview has completely consumed the interface.

How would it be possible to stop this behavior?. I don't want to use the max_height function on the scrollview as i still want the entire UI to be adaptive according to the window size rather than creating a hard limit.

**Comment by NathanSWard** [comment]
+1 for this

**Comment by hecrj** [comment]
This is caused by a limitation / bug of the current layout engine and widget implementation.

In order to fix this, you have to explicitly state `height(Length::Fill)` for all of the parent containers of the `Scrollable`.

In any case, we should really tackle this limitation soon. I will work on it right away!

**Comment by hecrj** [comment]
Fixed by #2192.

**Comment by lobneroO** [comment]
I think this is still happening with version 0.12. I have a scrollable which can become quite lengthy and two buttons beneath it. If the scrollable takes up more space than the window offers, it pushes the button out of the window.

[My proejct](https://github.com/lobneroO/pro-tool/commit/fc0f1fd650e8468e7eb7c491ff3b2e8554415d99)
You will have to choose the attached input file, then click "Create Personal Running Order".

Input file:
[data_summerbreeze2022.csv](https://github.com/user-attachments/files/16102841/data_summerbreeze2022.csv)


This is the default for me when it opens:
![image](https://github.com/iced-rs/iced/assets/17877050/eac65a65-456a-47eb-bb2e-e982d19cda27)

Then, enlarging the window to make everything fit:
![image](https://github.com/iced-rs/iced/assets/17877050/79972746-4eb3-441f-8330-d26951a4eb8c)

If there is barely space for the buttons, they are rendered very small (without text, I think)
![image](https://github.com/iced-rs/iced/assets/17877050/eefb718f-ed70-4f87-9ef7-d27dd386a96f)

The view is created in src/gui/band_selection_view.rs and src/band.rs (and excuse the hardcoded parts, this is still very much a work in progress).
